package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CapacidadTerminal generated by hbm2java
 */
@Entity
@Table(name="CAPACIDAD_TERMINAL"
    ,catalog="matriculacetpro"
)
public class CapacidadTerminal  implements java.io.Serializable {


     private int idCodigo;
     private Modulo modulo;
     private String nombreCt;
     private String notaCt;

    public CapacidadTerminal() {
    }

	
    public CapacidadTerminal(int idCodigo, Modulo modulo) {
        this.idCodigo = idCodigo;
        this.modulo = modulo;
    }
    public CapacidadTerminal(int idCodigo, Modulo modulo, String nombreCt, String notaCt) {
       this.idCodigo = idCodigo;
       this.modulo = modulo;
       this.nombreCt = nombreCt;
       this.notaCt = notaCt;
    }
   
     @Id 
    
    @Column(name="idCodigo", unique=true, nullable=false)
    public int getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(int idCodigo) {
        this.idCodigo = idCodigo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODULO_codModulo", nullable=false)
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    
    @Column(name="nombreCT", length=45)
    public String getNombreCt() {
        return this.nombreCt;
    }
    
    public void setNombreCt(String nombreCt) {
        this.nombreCt = nombreCt;
    }
    
    @Column(name="notaCT", length=45)
    public String getNotaCt() {
        return this.notaCt;
    }
    
    public void setNotaCt(String notaCt) {
        this.notaCt = notaCt;
    }




}


