package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrupoDiaId generated by hbm2java
 */
@Embeddable
public class GrupoDiaId  implements java.io.Serializable {


     private int diaIdDia;
     private int grupoIdGrupo;

    public GrupoDiaId() {
    }

    public GrupoDiaId(int diaIdDia, int grupoIdGrupo) {
       this.diaIdDia = diaIdDia;
       this.grupoIdGrupo = grupoIdGrupo;
    }
   

    @Column(name="DIA_idDia", nullable=false)
    public int getDiaIdDia() {
        return this.diaIdDia;
    }
    
    public void setDiaIdDia(int diaIdDia) {
        this.diaIdDia = diaIdDia;
    }

    @Column(name="GRUPO_idGrupo", nullable=false)
    public int getGrupoIdGrupo() {
        return this.grupoIdGrupo;
    }
    
    public void setGrupoIdGrupo(int grupoIdGrupo) {
        this.grupoIdGrupo = grupoIdGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupoDiaId) ) return false;
		 GrupoDiaId castOther = ( GrupoDiaId ) other; 
         
		 return (this.getDiaIdDia()==castOther.getDiaIdDia())
 && (this.getGrupoIdGrupo()==castOther.getGrupoIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDiaIdDia();
         result = 37 * result + this.getGrupoIdGrupo();
         return result;
   }   


}


