package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GrupoDia generated by hbm2java
 */
@Entity
@Table(name="GRUPO_DIA"
    ,catalog="matriculacetpro"
)
public class GrupoDia  implements java.io.Serializable {


     private GrupoDiaId id;
     private Grupo grupo;
     private Dia dia;
     private String descripcionGrupoDia;

    public GrupoDia() {
    }

	
    public GrupoDia(GrupoDiaId id, Grupo grupo, Dia dia) {
        this.id = id;
        this.grupo = grupo;
        this.dia = dia;
    }
    public GrupoDia(GrupoDiaId id, Grupo grupo, Dia dia, String descripcionGrupoDia) {
       this.id = id;
       this.grupo = grupo;
       this.dia = dia;
       this.descripcionGrupoDia = descripcionGrupoDia;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="diaIdDia", column=@Column(name="DIA_idDia", nullable=false) ), 
        @AttributeOverride(name="grupoIdGrupo", column=@Column(name="GRUPO_idGrupo", nullable=false) ) } )
    public GrupoDiaId getId() {
        return this.id;
    }
    
    public void setId(GrupoDiaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUPO_idGrupo", nullable=false, insertable=false, updatable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DIA_idDia", nullable=false, insertable=false, updatable=false)
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    
    @Column(name="descripcionGrupoDia", length=45)
    public String getDescripcionGrupoDia() {
        return this.descripcionGrupoDia;
    }
    
    public void setDescripcionGrupoDia(String descripcionGrupoDia) {
        this.descripcionGrupoDia = descripcionGrupoDia;
    }




}


