package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name="MODULO"
    ,catalog="matriculacetpro"
)
public class Modulo  implements java.io.Serializable {


     private int idModulo;
     private Especialidad especialidad;
     private String nombreModulo;
     private String horasModulo;
     private Set grupos = new HashSet(0);
     private Set capacidadTerminals = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int idModulo, Especialidad especialidad) {
        this.idModulo = idModulo;
        this.especialidad = especialidad;
    }
    public Modulo(int idModulo, Especialidad especialidad, String nombreModulo, String horasModulo, Set grupos, Set capacidadTerminals) {
       this.idModulo = idModulo;
       this.especialidad = especialidad;
       this.nombreModulo = nombreModulo;
       this.horasModulo = horasModulo;
       this.grupos = grupos;
       this.capacidadTerminals = capacidadTerminals;
    }
   
     @Id 
    
    @Column(name="idModulo", unique=true, nullable=false)
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ESPECIALIDAD_idEspecialidad", nullable=false)
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }
    
    @Column(name="nombreModulo", length=80)
    public String getNombreModulo() {
        return this.nombreModulo;
    }
    
    public void setNombreModulo(String nombreModulo) {
        this.nombreModulo = nombreModulo;
    }
    
    @Column(name="horasModulo", length=45)
    public String getHorasModulo() {
        return this.horasModulo;
    }
    
    public void setHorasModulo(String horasModulo) {
        this.horasModulo = horasModulo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modulo")
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modulo")
    public Set getCapacidadTerminals() {
        return this.capacidadTerminals;
    }
    
    public void setCapacidadTerminals(Set capacidadTerminals) {
        this.capacidadTerminals = capacidadTerminals;
    }




}


