package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="PROFESOR"
    ,catalog="matriculacetpro"
)
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private String nombres;
     private String apePaterno;
     private String apeMaterno;
     private Date fecNacimiento;
     private Character sexo;
     private Integer dni;
     private String email;
     private Integer edad;
     private Integer numFijo;
     private Integer numMovil;
     private String domicilio;
     private String gradEstudios;
     private Set grupos = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Profesor(int idProfesor, String nombres, String apePaterno, String apeMaterno, Date fecNacimiento, Character sexo, Integer dni, String email, Integer edad, Integer numFijo, Integer numMovil, String domicilio, String gradEstudios, Set grupos) {
       this.idProfesor = idProfesor;
       this.nombres = nombres;
       this.apePaterno = apePaterno;
       this.apeMaterno = apeMaterno;
       this.fecNacimiento = fecNacimiento;
       this.sexo = sexo;
       this.dni = dni;
       this.email = email;
       this.edad = edad;
       this.numFijo = numFijo;
       this.numMovil = numMovil;
       this.domicilio = domicilio;
       this.gradEstudios = gradEstudios;
       this.grupos = grupos;
    }
   
     @Id 
    
    @Column(name="idProfesor", unique=true, nullable=false)
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apePaterno", length=45)
    public String getApePaterno() {
        return this.apePaterno;
    }
    
    public void setApePaterno(String apePaterno) {
        this.apePaterno = apePaterno;
    }
    
    @Column(name="apeMaterno", length=45)
    public String getApeMaterno() {
        return this.apeMaterno;
    }
    
    public void setApeMaterno(String apeMaterno) {
        this.apeMaterno = apeMaterno;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecNacimiento", length=10)
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    
    @Column(name="sexo", length=1)
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="dni", precision=8, scale=0)
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    
    @Column(name="numFijo", precision=7, scale=0)
    public Integer getNumFijo() {
        return this.numFijo;
    }
    
    public void setNumFijo(Integer numFijo) {
        this.numFijo = numFijo;
    }
    
    @Column(name="numMovil", precision=9, scale=0)
    public Integer getNumMovil() {
        return this.numMovil;
    }
    
    public void setNumMovil(Integer numMovil) {
        this.numMovil = numMovil;
    }
    
    @Column(name="domicilio", length=45)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    
    @Column(name="gradEstudios", length=45)
    public String getGradEstudios() {
        return this.gradEstudios;
    }
    
    public void setGradEstudios(String gradEstudios) {
        this.gradEstudios = gradEstudios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="profesor")
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


