package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgCurricular generated by hbm2java
 */
@Entity
@Table(name="PROG_CURRICULAR"
    ,catalog="matriculacetpro"
)
public class ProgCurricular  implements java.io.Serializable {


     private int idProgCurricular;
     private Date fecRegistro;
     private String detalle;
     private Set curriculaAnuals = new HashSet(0);

    public ProgCurricular() {
    }

	
    public ProgCurricular(int idProgCurricular) {
        this.idProgCurricular = idProgCurricular;
    }
    public ProgCurricular(int idProgCurricular, Date fecRegistro, String detalle, Set curriculaAnuals) {
       this.idProgCurricular = idProgCurricular;
       this.fecRegistro = fecRegistro;
       this.detalle = detalle;
       this.curriculaAnuals = curriculaAnuals;
    }
   
     @Id 
    
    @Column(name="idProgCurricular", unique=true, nullable=false)
    public int getIdProgCurricular() {
        return this.idProgCurricular;
    }
    
    public void setIdProgCurricular(int idProgCurricular) {
        this.idProgCurricular = idProgCurricular;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecRegistro", length=10)
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    
    @Column(name="detalle", length=45)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="progCurricular")
    public Set getCurriculaAnuals() {
        return this.curriculaAnuals;
    }
    
    public void setCurriculaAnuals(Set curriculaAnuals) {
        this.curriculaAnuals = curriculaAnuals;
    }




}


