package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dia generated by hbm2java
 */
@Entity
@Table(name="DIA"
    ,catalog="matriculacetpro"
)
public class Dia  implements java.io.Serializable {


     private int idDia;
     private String nombreDia;
     private String nomDia;
     private Set grupoDias = new HashSet(0);

    public Dia() {
    }

	
    public Dia(int idDia) {
        this.idDia = idDia;
    }
    public Dia(int idDia, String nombreDia, String nomDia, Set grupoDias) {
       this.idDia = idDia;
       this.nombreDia = nombreDia;
       this.nomDia = nomDia;
       this.grupoDias = grupoDias;
    }
   
     @Id 
    
    @Column(name="idDia", unique=true, nullable=false)
    public int getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(int idDia) {
        this.idDia = idDia;
    }
    
    @Column(name="nombreDia", length=45)
    public String getNombreDia() {
        return this.nombreDia;
    }
    
    public void setNombreDia(String nombreDia) {
        this.nombreDia = nombreDia;
    }
    
    @Column(name="nomDia", length=45)
    public String getNomDia() {
        return this.nomDia;
    }
    
    public void setNomDia(String nomDia) {
        this.nomDia = nomDia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dia")
    public Set getGrupoDias() {
        return this.grupoDias;
    }
    
    public void setGrupoDias(Set grupoDias) {
        this.grupoDias = grupoDias;
    }




}


