package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResolucionDirectoral generated by hbm2java
 */
@Entity
@Table(name="RESOLUCION_DIRECTORAL"
    ,catalog="matriculacetpro"
)
public class ResolucionDirectoral  implements java.io.Serializable {


     private int idRd;
     private Integer anioInicio;
     private Integer anioTermino;
     private Date fecRegistro;
     private Set especialidads = new HashSet(0);

    public ResolucionDirectoral() {
    }

	
    public ResolucionDirectoral(int idRd) {
        this.idRd = idRd;
    }
    public ResolucionDirectoral(int idRd, Integer anioInicio, Integer anioTermino, Date fecRegistro, Set especialidads) {
       this.idRd = idRd;
       this.anioInicio = anioInicio;
       this.anioTermino = anioTermino;
       this.fecRegistro = fecRegistro;
       this.especialidads = especialidads;
    }
   
     @Id 
    
    @Column(name="idRD", unique=true, nullable=false)
    public int getIdRd() {
        return this.idRd;
    }
    
    public void setIdRd(int idRd) {
        this.idRd = idRd;
    }
    
    @Column(name="anioInicio")
    public Integer getAnioInicio() {
        return this.anioInicio;
    }
    
    public void setAnioInicio(Integer anioInicio) {
        this.anioInicio = anioInicio;
    }
    
    @Column(name="anioTermino")
    public Integer getAnioTermino() {
        return this.anioTermino;
    }
    
    public void setAnioTermino(Integer anioTermino) {
        this.anioTermino = anioTermino;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecRegistro", length=10)
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="resolucionDirectoral")
    public Set getEspecialidads() {
        return this.especialidads;
    }
    
    public void setEspecialidads(Set especialidads) {
        this.especialidads = especialidads;
    }




}


