package com.matricula.model;
// Generated 9/12/2013 01:55:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Turno generated by hbm2java
 */
@Entity
@Table(name="TURNO"
    ,catalog="matriculacetpro"
)
public class Turno  implements java.io.Serializable {


     private int idTurno;
     private String detalleTurno;
     private Date horaInicio;
     private Date horaTermino;
     private Set grupos = new HashSet(0);

    public Turno() {
    }

	
    public Turno(int idTurno) {
        this.idTurno = idTurno;
    }
    public Turno(int idTurno, String detalleTurno, Date horaInicio, Date horaTermino, Set grupos) {
       this.idTurno = idTurno;
       this.detalleTurno = detalleTurno;
       this.horaInicio = horaInicio;
       this.horaTermino = horaTermino;
       this.grupos = grupos;
    }
   
     @Id 
    
    @Column(name="idTurno", unique=true, nullable=false)
    public int getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(int idTurno) {
        this.idTurno = idTurno;
    }
    
    @Column(name="detalleTurno", length=45)
    public String getDetalleTurno() {
        return this.detalleTurno;
    }
    
    public void setDetalleTurno(String detalleTurno) {
        this.detalleTurno = detalleTurno;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="horaInicio", length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="horaTermino", length=8)
    public Date getHoraTermino() {
        return this.horaTermino;
    }
    
    public void setHoraTermino(Date horaTermino) {
        this.horaTermino = horaTermino;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="turno")
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


